<?php

namespace OcupacionEmpleoBundle\Repository;

/**
 * PertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PertRepository extends \Doctrine\ORM\EntityRepository
{
}
